"""Geopolitical Strategic Chokepoints, Conflict Flashpoints, and Global Elections Map Engine."""
from __future__ import annotations

from typing import Any


STRATEGIC_CHOKEPOINTS: list[dict[str, Any]] = [
    {
        "id": "strait_of_hormuz",
        "name": "Strait of Hormuz",
        "lat": 26.56,
        "lng": 56.25,
        "type": "maritime_chokepoint",
        "oil_transit_mbpd": 21.0,
        "share_of_global_oil_pct": 21.0,
        "primary_actors": ["Iran", "Oman", "United Arab Emirates", "US Fifth Fleet"],
        "security_status": "High Alert",
        "risk_tier": "Critical",
        "summary": "World's most critical petroleum transit chokepoint connecting Persian Gulf exporters with Asian and Western markets.",
    },
    {
        "id": "bab_el_mandeb",
        "name": "Bab-el-Mandeb Strait",
        "lat": 12.58,
        "lng": 43.33,
        "type": "maritime_chokepoint",
        "oil_transit_mbpd": 8.8,
        "share_of_global_oil_pct": 9.0,
        "primary_actors": ["Yemen (Ansar Allah)", "Djibouti", "Saudi Arabia", "Combined Maritime Forces"],
        "security_status": "Active Interdiction Threat",
        "risk_tier": "Severe",
        "summary": "Southern gateway to the Red Sea and Suez Canal facing asymmetric drone and anti-ship missile interdiction risks.",
    },
    {
        "id": "malacca_strait",
        "name": "Strait of Malacca",
        "lat": 4.21,
        "lng": 100.55,
        "type": "maritime_chokepoint",
        "oil_transit_mbpd": 16.0,
        "share_of_global_oil_pct": 16.0,
        "primary_actors": ["Singapore", "Malaysia", "Indonesia", "China"],
        "security_status": "Heavy Traffic / Strategic Dilemma",
        "risk_tier": "Elevated",
        "summary": "Primary maritime corridor connecting the Indian Ocean to East Asian manufacturing powerhouses.",
    },
    {
        "id": "suez_canal",
        "name": "Suez Canal",
        "lat": 30.70,
        "lng": 32.34,
        "type": "canal_chokepoint",
        "oil_transit_mbpd": 5.5,
        "share_of_global_oil_pct": 6.0,
        "primary_actors": ["Egypt", "European Union", "Global Liner Fleets"],
        "security_status": "Cape of Good Hope Diversion Pressure",
        "risk_tier": "Elevated",
        "summary": "Critical artificial waterway linking Europe and Asia; experiencing major traffic shifts due to Red Sea security risks.",
    },
    {
        "id": "taiwan_strait",
        "name": "Taiwan Strait",
        "lat": 24.00,
        "lng": 119.50,
        "type": "maritime_chokepoint",
        "oil_transit_mbpd": 0.0,
        "share_of_global_oil_pct": 0.0,
        "primary_actors": ["Taiwan", "China (PLA)", "United States", "Japan"],
        "security_status": "Grey-Zone Patrol Escalation",
        "risk_tier": "Critical",
        "summary": "Carries ~50% of the world's commercial container shipping fleet and connects high-end semiconductor supply chains.",
    },
    {
        "id": "panama_canal",
        "name": "Panama Canal",
        "lat": 9.08,
        "lng": -79.68,
        "type": "canal_chokepoint",
        "oil_transit_mbpd": 1.2,
        "share_of_global_oil_pct": 1.5,
        "primary_actors": ["Panama", "United States", "Latin America", "East Asia"],
        "security_status": "Freshwater Draft Restrictions",
        "risk_tier": "Moderate",
        "summary": "Crucial link between the Atlantic and Pacific oceans handling 5% of all global maritime cargo trade.",
    },
    {
        "id": "turkish_straits",
        "name": "Turkish Straits (Bosporus & Dardanelles)",
        "lat": 41.11,
        "lng": 29.06,
        "type": "maritime_chokepoint",
        "oil_transit_mbpd": 3.0,
        "share_of_global_oil_pct": 3.2,
        "primary_actors": ["Turkey", "Russia", "Ukraine", "Black Sea Littorals"],
        "security_status": "Montreux Convention Enforcement",
        "risk_tier": "Elevated",
        "summary": "Vital Black Sea export gateway for agricultural grain, fertilizer, and Eurasian crude oil exports.",
    },
]

CONFLICT_FLASHPOINTS: list[dict[str, Any]] = [
    {
        "id": "eastern_ukraine",
        "title": "Eastern Ukraine Combat Theater",
        "lat": 48.00,
        "lng": 37.80,
        "category": "Interstate War",
        "intensity": "High Intensity / Active Shelling",
        "summary": "Frontline defense lines, drone warfare, and infrastructure interdiction across Donbas and Southern oblasts.",
    },
    {
        "id": "gaza_levant",
        "title": "Gaza & Levant Border Corridor",
        "lat": 31.50,
        "lng": 34.45,
        "category": "Regional Conflict",
        "intensity": "High Intensity / Multi-Front",
        "summary": "Cross-border exchanges, urban combat, and broader regional deterrence posturing across the Northern border.",
    },
    {
        "id": "red_sea_security",
        "title": "Red Sea Shipping Corridor",
        "lat": 15.00,
        "lng": 41.50,
        "category": "Maritime Security",
        "intensity": "Asymmetric Interdiction",
        "summary": "Anti-ship ballistic missile and maritime drone operations targeting international commercial vessels.",
    },
    {
        "id": "sahel_alliance",
        "title": "Central Sahel Security Zone",
        "lat": 14.50,
        "lng": -1.00,
        "category": "Counter-Insurgency & Regime Security",
        "intensity": "Moderate to High",
        "summary": "AES military alliance operations combating insurgencies following Western troop withdrawals.",
    },
    {
        "id": "sudan_khartoum",
        "title": "Sudanese Civil Conflict",
        "lat": 15.50,
        "lng": 32.50,
        "category": "Civil War & Humanitarian Crisis",
        "intensity": "Severe Humanitarian Fallout",
        "summary": "Protracted armed clashes between SAF and RSF causing severe displacement and regional spillover.",
    },
    {
        "id": "korean_peninsula",
        "title": "Korean Peninsula Demarcation Line",
        "lat": 38.00,
        "lng": 127.00,
        "category": "Strategic Deterrence",
        "intensity": "Deterrence Maneuvers & Drills",
        "summary": "Hypersonic and ballistic missile launches accompanied by combined joint carrier exercises.",
    },
]

GLOBAL_ELECTIONS: list[dict[str, Any]] = [
    {
        "country": "United States",
        "flag": "🇺🇸",
        "lat": 38.90,
        "lng": -77.03,
        "date": "2026-11-03",
        "event": "US Midterm Congressional Elections",
        "stakes": "Control of House and Senate, trade policy and judiciary nominations.",
    },
    {
        "country": "Germany",
        "flag": "🇩🇪",
        "lat": 52.52,
        "lng": 13.40,
        "date": "2026-09-27",
        "event": "Bundestag Federal Elections",
        "stakes": "Industrial transition, defense budgets, and EU fiscal governance alignment.",
    },
    {
        "country": "Brazil",
        "flag": "🇧🇷",
        "lat": -15.79,
        "lng": -47.88,
        "date": "2026-10-04",
        "event": "General Presidential Election",
        "stakes": "Macroeconomic fiscal rules, Amazon conservation, and BRICS geopolitical positioning.",
    },
    {
        "country": "Japan",
        "flag": "🇯🇵",
        "lat": 35.67,
        "lng": 139.65,
        "date": "2026-10-25",
        "event": "House of Representatives Election",
        "stakes": "Defense spending targets, monetary policy normalization, and semiconductor subsidies.",
    },
]


def get_geopolitical_map_layers() -> dict[str, Any]:
    """Retrieve all structured geopolitical overlays: chokepoints, conflict flashpoints, and election tracker."""
    return {
        "chokepoints": STRATEGIC_CHOKEPOINTS,
        "conflict_flashpoints": CONFLICT_FLASHPOINTS,
        "elections": GLOBAL_ELECTIONS,
        "total_chokepoints": len(STRATEGIC_CHOKEPOINTS),
        "total_flashpoints": len(CONFLICT_FLASHPOINTS),
        "total_elections": len(GLOBAL_ELECTIONS),
    }
